### ISSUE TITLE
No clear on how to set up

### ISSUE THREAD

**Issue by deepcoder** [djtimca/handbc#2]
Thank you for creating these interesting add ons to Home Assistant.

I am not clear on how to get this up and operating. I tried searching for the name in HACS and came up empty. Then I created the:
```
custom_components/ndberealtime 
```
folder and placed the file in this folder from the download at GitHub.

I do not know the next step.

Thx!

**Comment by olyashok** [comment]
- Install HACS
- Go to HACS -> Integrations, click on "..." in top right, add new repository with "https://github.com/djtimca/handbc"
- Click on "+ Add Integration", search for NDBC

**Comment by deepcoder** [comment]
Thank you for the information, your steps worked.
