### ISSUE TITLE
Constant "DEGREES" not found.

### ISSUE THREAD

**Issue by greenbus4** [djtimca/handbc#4]
In commit [74d6dd9](https://github.com/djtimca/handbc/commit/74d6dd9f0368565d95bc2c4364bbf048e0b909df) on May 2, 2024 the constant `DEGREE` was changed to `DEGREES`, but I'm not seeing that change in HA's const.py as of version 2024.5.5, which I'm running:

https://github.com/home-assistant/core/blob/2024.5.5/homeassistant/const.py#L740

Not sure I trust my search skills, but I haven't found were that change is proposed in core.

Thanks

**Comment by djtimca** [comment]
Fixed in https://github.com/djtimca/handbc/commit/d97e24bcd88cc3ef5adee65a90f80fea04f06cf4
